In [ ]:
import pandas as pd
import seaborn as sns

Available pre-trained models for sentiment analysis

1. VADERS from NLTK
2. Transformer models from Hugging Face: Roberta-model
3. Transfomer pipeline

In [47]:
tweet_data = pd.read_csv("C:/Users/Hp Pc/Downloads/sentiment-emotion-labelled_Dell_tweets.csv")
tweet_test = pd.read_csv("C:/Users/Hp Pc/Downloads/testdata.manual.2009.06.14.csv")

In [48]:
tweet_data.head(10)

,Unnamed: 0,Datetime,Tweet Id,Text,Username,sentiment,sentiment_score,emotion,emotion_score
0,0,2022-09-30 23:29:15+00:00,1575991191170342912,@Logitech @apple @Google @Microsoft @Dell @Len...,ManjuSreedaran,neutral,0.853283,anticipation,0.587121
1,1,2022-09-30 21:46:35+00:00,1575965354425131008,@MK_habit_addict @official_stier @MortalKombat...,MiKeMcDnet,neutral,0.519470,joy,0.886913
2,2,2022-09-30 21:18:02+00:00,1575958171423752203,"As¬†@CRN¬†celebrates its 40th anniversary,¬†Bob F...",jfollett,positive,0.763791,joy,0.960347
3,3,2022-09-30 20:05:24+00:00,1575939891485032450,@dell your customer service is horrible especi...,daveccarr,negative,0.954023,anger,0.983203
4,4,2022-09-30 20:03:17+00:00,1575939359160750080,@zacokalo @Dell @DellCares @Dell give the man ...,heycamella,neutral,0.529170,anger,0.776124
5,5,2022-09-30 19:49:40+00:00,1575935931969785856,The screenshot is acting up from the website o...,jonathanj92389,negative,0.936235,sadness,0.968651
6,6,2022-09-30 19:31:57+00:00,1575931475391746048,@emijuju_ @Alienware @Dell @IntelGaming alien ...,diegoaygo,neutral,0.733473,fear,0.370504
7,7,2022-09-30 19:25:45+00:00,1575929914888421395,COOKING STREAM DAY!!! Ty to @Alienware for spo...,emijuju_,positive,0.974963,joy,0.961772
8,8,2022-09-30 19:07:30+00:00,1575925320070623232,@emijuju_ @Alienware @Dell @intel Beautiful üòç‚ù§Ô∏èüòª,Khurram38256043,positive,0.974661,joy,0.986383
9,9,2022-09-30 19:02:37+00:00,1575924090187153416,What's your biggest data management challenge?...,InfoSystems,neutral,0.718806,optimism,0.894296

In [49]:
tweet_test.columns

Index(['4', '3', 'Mon May 11 03:17:40 UTC 2009', 'kindle2', 'tpryan',
       '@stellargirl I loooooooovvvvvveee my Kindle2. Not that the DX is cool, but the 2 is fantastic in its own right.'],
      dtype='object')

In [50]:
tweet_test.columns = ['score', 'number', "date", "account", "username","text"]

CLEANING DATA AND EPA

In [51]:
tweet_data = tweet_data.drop(columns = ['Unnamed: 0', 'Tweet Id'], axis=1)
tweet_data['Datetime'] = pd.to_datetime(tweet_data["Datetime"])

In [52]:
tweet_data.dtypes

Datetime           datetime64[ns, UTC]
Text                            object
Username                        object
sentiment                       object
sentiment_score                float64
emotion                         object
emotion_score                  float64
dtype: object

In [53]:
print(tweet_data['sentiment'].value_counts())
print(tweet_data['emotion'].value_counts())

sentiment
negative    10556
positive     7366
neutral      7048
Name: count, dtype: int64
emotion
anger           7520
joy             6326
anticipation    5171
disgust         3000
sadness         1328
optimism        1225
fear             366
surprise          34
Name: count, dtype: int64

In [54]:
tweet_data['year'] = tweet_data['Datetime'].dt.year

In [70]:
tweet_data.head()

,Datetime,Text,Username,sentiment,sentiment_score,emotion,emotion_score,year
0,2022-09-30 23:29:15+00:00,@Logitech @apple @Google @Microsoft @Dell @Len...,ManjuSreedaran,neutral,0.853283,anticipation,0.587121,2022
1,2022-09-30 21:46:35+00:00,@MK_habit_addict @official_stier @MortalKombat...,MiKeMcDnet,neutral,0.519470,joy,0.886913,2022
2,2022-09-30 21:18:02+00:00,"As¬†@CRN¬†celebrates its 40th anniversary,¬†Bob F...",jfollett,positive,0.763791,joy,0.960347,2022
3,2022-09-30 20:05:24+00:00,@dell your customer service is horrible especi...,daveccarr,negative,0.954023,anger,0.983203,2022
4,2022-09-30 20:03:17+00:00,@zacokalo @Dell @DellCares @Dell give the man ...,heycamella,neutral,0.529170,anger,0.776124,2022

In [ ]:
fig, axes = plt.subplots(1,2, figsize=(8,4))
axes[0,0] = tweet_data[['year', 'sentiment']].plot(kind='bar')

In [ ]:
plt.figure(figsize=(15,10))
year_sentiments = tweet_data[['year', 'sentiment']].sort_values('year')

plot = sns.countplot(data=year_sentiment, x='year', hue='class', width=0.7, palette=['blue', 'yellow'])
plot.legend(title='Year on Year Analysis', labels=['Happy', 'Sad'])
plt.title('Year on Year Report')
plt.show()

In [ ]:
plt.figure(figsize=(15,10))
year_emotion = tweet_data[['year', 'emotion']].sort_values('year')

plot = sns.countplot(data=year_emotion, x='year', hue='class', width=0.7)
plot.legend(title='Year on Year Analysis', labels=['Happy', 'Sad'])
plt.title('Year on Year Report')
plt.show()

In [25]:
sents_map = {
    "negative":0,
    "positive": 2,
    "neutral" : 1
}

tweet_data['sentiment'] = tweet_data['sentiment'].map(sents_map)

In [36]:
good_emotions = ['joy', 'anticipation', 'optimism', 'surprise']

def good_bad(column):
    for i, word in column.values:
        for emotion in good_emotions:
            if word == emotion:
                column[i] = 2
            else:
                column[i] = 1
    return column

In [45]:
emotion_map = {
    'anger': 1,
    'joy': 2,       
    'anticipation': 2,  
    'disgust': 1,         
    'sadness': 1,
    'optimism': 2,       
    'fear': 1,            
    'surprise': 2 
}

tweet_data['emotion'] = tweet_data['emotion'].map(emotion_map)

In [46]:
tweet_data.head()

,Datetime,Text,Username,sentiment,sentiment_score,emotion,emotion_score
0,2022-09-30 23:29:15+00:00,@Logitech @apple @Google @Microsoft @Dell @Len...,ManjuSreedaran,1.0,0.853283,2,0.587121
1,2022-09-30 21:46:35+00:00,@MK_habit_addict @official_stier @MortalKombat...,MiKeMcDnet,1.0,0.519470,2,0.886913
2,2022-09-30 21:18:02+00:00,"As¬†@CRN¬†celebrates its 40th anniversary,¬†Bob F...",jfollett,NaN,0.763791,2,0.960347
3,2022-09-30 20:05:24+00:00,@dell your customer service is horrible especi...,daveccarr,0.0,0.954023,1,0.983203
4,2022-09-30 20:03:17+00:00,@zacokalo @Dell @DellCares @Dell give the man ...,heycamella,1.0,0.529170,1,0.776124